### PR TITLE
Fix TC_Encoder::gbk2utf8 invalid pointer exception

### PR DESCRIPTION
**Pull request by wincsb**
Roll back the previous version code

### CODE REVIEW

**Comment by ruanshudong** [comment]
这个改动是还原了? 新的代码有bug?

**Comment by wincsb** [comment]
只是还原。新代码,一调用就会异常退出。
项目中这个函数已经在很多地方使用。

**Comment by libjjc** [comment]
> 只是还原。新代码,一调用就会异常退出。
> 项目中这个函数已经在很多地方使用。

你好，新代码中确实默认是兼容更早的版本，在更早的版本中如果遇到未录入字符则会抛出异常。我在基于新版本修改的时候也发现新版本似乎修正这个问题，只是方式上感觉不太友好。我认为如果有需要，可以修改一下转换模式的默认参数（TRANSLIT OR IGNORE）即可。

**Comment by ruanshudong** [comment]
我计划gbk2utf8的缺省值改成ICONV_IGNORE

**Comment by wincsb** [comment]
今天更新2.4.10测试用 ICONV_IGNORE 版本仍然会挂。

item.Name:<C2><DE><D7><E2><C0>ϴ嶫10<C7><F8>14<BA><C5>¥<C4><DA>
*** Error in `/usr/local/app/tars/tarsnode/data/XX.NetManagerServer/bin/NetManagerServer': munmap_chunk(): invalid pointer: 0x00007ff3fc2850
af ***
======= Backtrace: =========
/usr/lib64/libc.so.6(+0x7ab54)[0x7ff42851ab54]
/usr/local/app/tars/tarsnode/data/XX.NetManagerServer/bin/NetManagerServer(_ZN4tars10TC_Encoder8gbk2utf8ERKSsi+0xf2)[0x58d5d2]
/usr/local/app/tars/tarsnode/data/XX.NetManagerServer

**Comment by ruanshudong** [comment]
嗯, 发现了, 正在看, 这代码改出bug了

**Comment by ruanshudong** [comment]
@wincsb , tarscpp master我推了一个版本上去, 你看看是否可以了, 我这边测试貌似没问题了

**Comment by wincsb** [comment]
@ ruanshudong  更新了，还是会core.....

*** Error in `/usr/local/app/tars/tarsnode/data/XhVideOnTars.PtzControlServer/bin/PtzControlServer': malloc(): memory corruption: 0x00007f0a340019c0 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x7dd7d)[0x7f0ab7831d7d]
/lib64/libc.so.6(__libc_malloc+0x4c)[0x7f0ab783410c]
/usr/local/app/tars/tarsnode/data/XhVideOnTars.PtzControlServer/bin/PtzControlServer(_Znwm+0x18)[0x109c518]
/usr/local/app/tars/tarsnode/data/XhVideOnTars.PtzControlServer/bin/PtzControlServer(_ZNSs4_Rep9_S_createEmmRKSaIcE+0x59)[0x10e7349]
/usr/local/app/tars/tarsnode/data/XhVideOnTars.PtzControlServer/bin/PtzControlServer(_ZNSs9_M_mutateEmmm+0x54)[0x10e73c4]
/usr/local/app/tars/tarsnode/data/XhVideOnTars.PtzControlServer/bin/PtzControlServer(_ZNSs15_M_replace_safeEmmPKcm+0x1e)[0x10e79de]
/usr/local/app/tars/tarsnode/data/XhVideOnTars.PtzControlServer/bin/PtzControlServer(_ZN4tars10TC_Encoder8gbk2utf8ERKSsi+0xe6)[0x105c626]
/usr/local/app/tars/tarsnode/data/XhVideOnTars.PtzControlServer/bin/PtzControlServer(_ZN8hkSDKImp9getPresetERSsS0_+0x78f)[0x8627df]
/usr/local/app/tars/tarsnode/data/XhVideOnTars.PtzControlServer/bin/PtzControlServer(_ZN8hkSDKImp3PtzEiRSsS0_+0x64)[0x857384]
/usr/local/app/tars/tarsnode/data/XhVideOnTars.PtzControlServer/bin/PtzControlServer(_ZN13PtzControlImp9getPresetERKN12XhVideOnTars12GetPresetReqERNS0_12GetPresetRspEN4tars10TC_AutoPtrINS6_7CurrentEEE+0x1f3)[0xdbbea3]
/usr/local/app/tars/tarsnode/data/XhVideOnTars.PtzControlServer/bin/PtzControlServer(_ZN12XhVideOnTars12XHPtzControl10onDispatchEN4tars10TC_AutoPtrINS1_7CurrentEEERSt6vectorIcSaIcEE+0x61f)[0xdd69ef]
/usr/local/app/tars/tarsnode/data/XhVideOnTars.PtzControlServer/bin/PtzControlServer(_ZN4tars7Servant8dispatchENS_10TC_AutoPtrINS_7CurrentEEERSt6vectorIcSaIcEE+0xb5)[0xffdc15]
/usr/local/app/tars/tarsnode/data/XhVideOnTars.PtzControlServer/bin/PtzControlServer(_ZN4tars13ServantHandle18handleTarsProtocolERKNS_10TC_AutoPtrINS_7CurrentEEE+0x4f5)[0x1004db5]
/usr/local/app/tars/tarsnode/data/XhVideOnTars.PtzControlServer/bin/PtzControlServer(_ZN4tars13ServantHandle6handleERKSt10shared_ptrINS_14TC_EpollServer11RecvContextEE+0x75)[0x1005cc5]
/usr/local/app/tars/tarsnode/data/XhVideOnTars.PtzControlServer/bin/PtzControlServer(_ZN4tars14TC_EpollServer6Handle9handleImpEv+0x1c3)[0x1064af3]
/usr/local/app/tars/tarsnode/data/XhVideOnTars.PtzControlServer/bin/PtzControlServer(_ZN4tars13ServantHandle3runEv+0x2b)[0x1000d2b]
/usr/local/app/tars/tarsnode/data/XhVideOnTars.PtzControlServer/bin/PtzControlServer(_ZN4tars9TC_Thread11threadEntryEPS0_+0x3a)[0x10902da]
/usr/local/app/tars/tarsnode/data/XhVideOnTars.PtzControlServer/bin/PtzControlServer[0x10ded20]
/lib64/libpthread.so.0(+0x7e25)[0x7f0abd1ffe25]
/lib64/libc.so.6(clone+0x6d)[0x7f0ab78ac34d]
======= Memory map: ========
00400000-01458000 r-xp 00000000 fd:00 186284276 /usr/local/app/tars/tarsnode/data/XhVideOnTars.PtzControlServer/bin/PtzControlServer
01657000-016d2000 r--p 01057000 fd:00 186284276 /usr/local/app/tars/tarsnode/data/XhVideOnTars.PtzControlServer/bin/PtzControlServer
016d2000-016d9000 rw-p 010d2000 fd:00 186284276 /usr/local/app/tars/tarsnode/data/XhVideOnTars.PtzControlServer/bin/PtzControlServer
016d9000-016f3000 rw-p 00000000 00:00 0
03146000-03a08000 rw-p 00000000 00:00 0 [heap]
7f0a20000000-7f0a20021000 rw-p 00000000 00:00 0
7f0a20021000-7f0a24000000 ---p 00000000 00:00 0
7f0a24000000-7f0a24021000 rw-p 00000000 00:00 0
7f0a24021000-7f0a28000000 ---p 00000000 00:00 0
7f0a28000000-7f0a28021000 rw-p 00000000 00:00 0
7f0a28021000-7f0a2c000000 ---p 00000000 00:00 0
7f0a2c000000-7f0a2c021000 rw-p 00000000 00:00 0
7f0a2c021000-7f0a30000000 ---p 00000000 00:00 0
7f0a31f4e000-7f0a31f69000 r-xp 00000000 fd:00 268675659 /usr/lib64/gconv/GBK.so
7f0a31f69000-7f0a32168000 ---p 0001b000 fd:00 268675659 /usr/lib64/gconv/GBK.so

**Pull request closed without merging**
